### ISSUE TITLE
SSL Certificate verification fail while downloading example data

### ISSUE THREAD

**Issue by santoshmh** [nithyanandan/PRISim#3]
After PRISim and the prerequisite packages were installed, an error was generated on executing the _setup_prisim_data.py_ script to download the example data inputs for PRISim. This error did not surface in previous PRISim installations.

The error is as follows:
>(PRISim-dev) santoshmh@enterprise:/data3/users/santoshmh/dev/PRISim$ setup_prisim_data.py
Downloading PRISim package data from http://www.dropbox.com/s/7y9go1bzjfa0rkv/prisim_data.tar.gz?dl=1 ...
Traceback (most recent call last):
  File "/home/santoshmh/src/anaconda/envs/PRISim-dev/bin/setup_prisim_data.py", line 98, in <module>
    download(url=parms[action_type]['url'], outfile=parms[action_type]['fname'], verbose=parms['verbose'])
  File "/home/santoshmh/src/anaconda/envs/PRISim-dev/bin/setup_prisim_data.py", line 27, in download
    r = requests.get(url)
  File "/home/santoshmh/src/anaconda/envs/PRISim-dev/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/santoshmh/src/anaconda/envs/PRISim-dev/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/santoshmh/src/anaconda/envs/PRISim-dev/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/santoshmh/src/anaconda/envs/PRISim-dev/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/santoshmh/src/anaconda/envs/PRISim-dev/lib/python2.7/site-packages/requests/sessions.py", line 177, in resolve_redirects
    **adapter_kwargs
  File "/home/santoshmh/src/anaconda/envs/PRISim-dev/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/santoshmh/src/anaconda/envs/PRISim-dev/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by nithyanandan** [comment]
As a temporary workaround, download the [prisim_data.tar.gz file ](https://drive.google.com/open?id=0Bxl4zmCNSW4tWnJmMDlBVHRQazQ) and extract in the installed PRISim folder. For example, if PRISim is installed in `/path/to/installed/prisim/`, then 
1. download [prisim_data.tar.gz file ](https://drive.google.com/open?id=0Bxl4zmCNSW4tWnJmMDlBVHRQazQ) into that folder, 
2. `cd /path/to/installed/prisim/`
3. `tar -xzvf prisim_data.tar.gz`, this will create a 'data' folder under `/path/to/installed/prisim/` as `/path/to/installed/prisim/data/`
4. After successful extraction, you can either delete or move the prisim_data.tar.gz out of the folder.

**Comment by nithyanandan** [comment]
Fixed in  9662bf2 
Now fully automated but works only with files on Google Drive
