### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by parphyam** [nithyanandan/PRISim#35]
Hello,
I cloned the repository and on doing pip install .  in the cloned directory I get the following error:
`Collecting git+https://github.com/nithyanandan/PRISim
  Cloning https://github.com/nithyanandan/PRISim to /tmp/pip-req-build-xZP4E7
Requirement already satisfied: astropy<3.0,>=1.0 in ./anaconda2/lib/python2.7/site-packages (from PRISim==0.1.0) (2.0.9)
Collecting astroutils@ git+git://github.com/nithyanandan/AstroUtils from git+git://github.com/nithyanandan/AstroUtils (from PRISim==0.1.0)
  Cloning git://github.com/nithyanandan/AstroUtils to /tmp/pip-install-lMLbgQ/astroutils
    Complete output from command python setup.py egg_info:
    /tmp/easy_install-m6gZ9r/astroquery-0.3.10.dev5705/astropy_helpers/astropy_helpers/git_helpers.py:118: UserWarning: No git repository present at '/tmp/easy_install-m6gZ9r/astroquery-0.3.10.dev5705'! Using default dev version.
      'default dev version.'.format(path))
    astroquery/mpc/setup_package.py:2: RuntimeWarning: Parent module 'astroquery.mpc' not found while handling absolute import
      import os
    astroquery/sdss/setup_package.py:2: RuntimeWarning: Parent module 'astroquery.sdss' not found while handling absolute import
      import os
    astroquery/astrometry_net/tests/setup_package.py:2: RuntimeWarning: Parent module 'astroquery.astrometry_net.tests' not found while handling absolute import
      import os
    astroquery/cds/tests/setup_package.py:1: RuntimeWarning: Parent module 'astroquery.cds.tests' not found while handling absolute import
      import os
    astroquery/mast/tests/setup_package.py:1: RuntimeWarning: Parent module 'astroquery.mast.tests' not found while handling absolute import
      import os
    astroquery/nasa_ads/tests/setup_package.py:1: RuntimeWarning: Parent module 'astroquery.nasa_ads.tests' not found while handling absolute import
      import os
    
    Installed /tmp/pip-install-lMLbgQ/astroutils/.eggs/astroquery-0.3.10.dev0-py2.7.egg
    Searching for pytest-runner
    Reading https://pypi.org/simple/pytest-runner/
    Downloading https://files.pythonhosted.org/packages/f8/31/f291d04843523406f242e63b5b90f7b204a756169b4250ff213e10326deb/pytest_runner-5.1-py2.py3-none-any.whl#sha256=d04243fbf29a3b574f18f1bcff2a07f505db5daede82f706f2e32728f77d3f4d
    Best match: pytest-runner 5.1
    Processing pytest_runner-5.1-py2.py3-none-any.whl
    Installing pytest_runner-5.1-py2.py3-none-any.whl to /tmp/pip-install-lMLbgQ/astroutils/.eggs
    writing requirements to /tmp/pip-install-lMLbgQ/astroutils/.eggs/pytest_runner-5.1-py2.7.egg/EGG-INFO/requires.txt
    
    Installed /tmp/pip-install-lMLbgQ/astroutils/.eggs/pytest_runner-5.1-py2.7.egg
    Searching for pyephem>=3.7.5.3
    Reading https://pypi.org/simple/pyephem/
    Downloading https://files.pythonhosted.org/packages/e7/d2/bc73bcf8ab21c2506e45aa8cff83bac9dd5d0df1428ab500610077684bb4/pyephem-3.7.7.0.tar.gz#sha256=e1f3d455a780abe8afa7f2c7a76f70449f53c9147a20285c3c708cebeea63bf4
    Best match: pyephem 3.7.7.0
    Processing pyephem-3.7.7.0.tar.gz
    Writing /tmp/easy_install-BE_MPc/pyephem-3.7.7.0/setup.cfg
    Running pyephem-3.7.7.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BE_MPc/pyephem-3.7.7.0/egg-dist-tmp-HKNMuo
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lMLbgQ/astroutils/setup.py", line 54, in <module>
        zip_safe=False)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/work/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/work/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/work/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/sandbox.py", line 233, in run_setup
        with setup_context(setup_dir):
      File "/home/work/anaconda2/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/work/anaconda2/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/sandbox.py", line 194, in setup_context
        __import__('setuptools')
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/__init__.py", line 18, in <module>
        import setuptools.version
      File "/home/work/anaconda2/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/work/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 84, in <module>
        __import__('pkg_resources.extern.packaging.requirements')
      File "/home/work/anaconda2/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
        __import__(extant)
      File "/home/work/anaconda2/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
        from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
      File "/home/work/anaconda2/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
        __import__(extant)
      File "/home/work/anaconda2/lib/python2.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 966, in <module>
        MutableMapping.register(ParseResults)
      File "/home/work/anaconda2/lib/python2.7/abc.py", line 109, in register
        if issubclass(subclass, cls):
      File "/home/work/anaconda2/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/home/work/anaconda2/lib/python2.7/site-packages/typing.py", line 1250, in __subclasscheck__
        return super(GenericMeta, self).__subclasscheck__(cls)
    TypeError: super() argument 1 must be type, not None
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-lMLbgQ/astroutil`

I found that this error is generally remedied by doing
 `sudo pip install --upgrade setuptools`. 
However that did not work, I am still getting this error. Can you kindly suggest how I should proceed?

**Comment by parphyam** [comment]
Just for your information I am working in a CentOS 7 machine, with anaconda2 and Python 2.7.16.

**Comment by nithyanandan** [comment]
I've not had this experience, and I've only installed on RedHat and Ubuntu systems. My only guess is that there may be some other package that is breaking something. 

Please let me know if you manage to fix it and the steps you took.
